"""add platform accounts table

Revision ID: 2260fc5ab639
Revises: 47b363753d0d
Create Date: 2026-02-14 11:23:10.236358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2260fc5ab639'
down_revision = '47b363753d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'platform_name', name='unique_student_platform')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_accounts')
    # ### end Alembic commands ###
