"""add status field to snapshots

Revision ID: 359eb9e00375
Revises: 247c09421de0
Create Date: 2026-02-14 20:18:16.129736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359eb9e00375'
down_revision = '247c09421de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_counsellors',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('counsellor_user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('department_id', 'counsellor_user_id')
    )
    op.create_table('student_advisors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('advisor_user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    with op.batch_alter_table('platform_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('remarks')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('status')

    op.drop_table('student_advisors')
    op.drop_table('department_counsellors')
    # ### end Alembic commands ###
