"""add platform snapshots table

Revision ID: 69156e2ac428
Revises: 2260fc5ab639
Create Date: 2026-02-14 11:26:52.280328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69156e2ac428'
down_revision = '2260fc5ab639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform_account_id', sa.String(length=36), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('contest_rating', sa.Integer(), nullable=True),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_account_id', 'snapshot_date', name='unique_platform_snapshot_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_snapshots')
    # ### end Alembic commands ###
