"""Added StudentCounsellor table

Revision ID: 81aa95498de8
Revises: a6d05ec0909b
Create Date: 2026-02-15 10:54:28.942632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81aa95498de8'
down_revision = 'a6d05ec0909b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_counsellors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('counsellor_user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_counsellors')
    # ### end Alembic commands ###
